spring.application.name=ExpenseTracker_v1
spring.datasource.url=jdbc:postgresql://localhost:5432/ExpenseTracker
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

logging.file.name=logs/expense-tracker.log
logging.level.root=INFO
logging.level.com.nilabja.ExpenseTracker=INFO
